import Link from "next/link";
import { AlertTriangle, FileText } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { UserSidebar } from "@/components/users/user-sidebar";
import {
  autoGenerateDoc,
  REPORT_CONFIG,
  ReportsContent,
  type Certification,
  type ReportDoc,
} from "./reports-content";

export default async function ReportTypePage({
  params,
  searchParams,
}: {
  params: Promise<{ type: string }>;
  searchParams: Promise<{ user?: string }>;
}) {
  const [{ type: reportType }, { user: userId }] = await Promise.all([params, searchParams]);
  const config = REPORT_CONFIG[reportType];

  if (!config) {
    return (
      <div className="flex flex-col items-center justify-center py-24 text-gray-500">
        <AlertTriangle size={40} className="mb-3 text-amber-400" />
        <p className="text-lg font-semibold text-gray-700">不明な帳票種別です</p>
        <Link href="/reports" className="mt-4 text-sm text-blue-600 hover:underline">帳票一覧に戻る</Link>
      </div>
    );
  }

  const isCertLinked = ["care-plan-1", "care-plan-2", "care-plan-3"].includes(reportType);

  let initialDocs: ReportDoc[] = [];
  let initialCertifications: Certification[] = [];

  if (userId) {
    const supabase = await createClient();

    let initialCertId: string | null = null;
    if (isCertLinked) {
      const { data } = await supabase
        .from("client_insurance_records")
        .select("id, care_level, start_date:certification_start_date, end_date:certification_end_date")
        .eq("client_id", userId)
        .order("certification_start_date", { ascending: false, nullsFirst: false });
      initialCertifications = (data ?? []) as Certification[];
      initialCertId = initialCertifications[0]?.id ?? null;
    }

    let q = supabase
      .from("kaigo_report_documents")
      .select("*")
      .eq("user_id", userId)
      .eq("report_type", reportType);
    if (isCertLinked && initialCertId) q = q.eq("certification_id", initialCertId);
    const { data: docData } = await q.order("updated_at", { ascending: false });
    initialDocs = (docData ?? []) as ReportDoc[];

    // 既存帳票が無ければ自動生成 (server side)
    if (initialDocs.length === 0) {
      try {
        const doc = await autoGenerateDoc(
          supabase,
          userId,
          reportType,
          config.needsPeriod ? new Date().toISOString().slice(0, 7) : null,
          config,
          isCertLinked ? initialCertId : null,
        );
        if (doc) initialDocs = [doc];
      } catch {
        // 認証や RLS 失敗時は client 側で再試行されるので無視
      }
    }
  }

  return (
    <div className="flex h-full -m-6">
      <UserSidebar />
      {userId ? (
        <ReportsContent
          key={`${userId}|${reportType}`}
          userId={userId}
          reportType={reportType}
          initialDocs={initialDocs}
          initialCertifications={initialCertifications}
        />
      ) : (
        <div className="flex-1 overflow-y-auto p-6">
          <div className="flex flex-col items-center justify-center py-24 text-gray-400 no-print">
            <FileText size={48} className="mb-4 text-gray-300" />
            <p className="text-base font-medium">左側のリストから利用者を選択してください</p>
          </div>
        </div>
      )}
    </div>
  );
}
