import Link from "next/link";
import { AlertTriangle, FileText } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { UserSidebar } from "@/components/users/user-sidebar";
import { REPORT_CONFIG } from "./report-config";
import {
  ReportsContent,
  type Certification,
  type ReportDoc,
} from "./reports-content";

export default async function ReportTypePage({
  params,
  searchParams,
}: {
  params: Promise<{ type: string }>;
  searchParams: Promise<{ user?: string }>;
}) {
  const [{ type: reportType }, { user: userId }] = await Promise.all([params, searchParams]);
  const config = REPORT_CONFIG[reportType];

  if (!config) {
    return (
      <div className="flex flex-col items-center justify-center py-24 text-gray-500">
        <AlertTriangle size={40} className="mb-3 text-amber-400" />
        <p className="text-lg font-semibold text-gray-700">不明な帳票種別です</p>
        <Link href="/reports" className="mt-4 text-sm text-blue-600 hover:underline">帳票一覧に戻る</Link>
      </div>
    );
  }

  const isCertLinked = ["care-plan-1", "care-plan-2", "care-plan-3", "yobo-care-plan"].includes(reportType);

  let initialDocs: ReportDoc[] = [];
  let initialCertifications: Certification[] = [];

  if (userId) {
    const supabase = await createClient();

    // 並列 fetch: cert と docs を完全に同時取得する。
    // 旧実装は「cert を await → 最新 cert id で docs を .eq() 絞り込み」の直列 2 往復
    // だったが、docs は cert filter 無しで全件取得しておき、cert 結果が出た後に
    // server 側 (この page 内) で最新 cert id に filter する方式に変更。
    // 結果は旧実装の .eq("certification_id", certId) と同一 (null cert の doc も
    // 同様に除外される) ので UI のチラつきも増えない。1 利用者 × 1 帳票種別の
    // docs は高々数十件なので全件取得のコストは無視できる。
    // 「無ければ autoGenerateDoc」は server では走らせない (client 側 fallback)。
    const docsPromise = supabase
      .from("kaigo_report_documents")
      .select("*")
      .eq("user_id", userId)
      .eq("report_type", reportType)
      .order("updated_at", { ascending: false });

    if (isCertLinked) {
      const certPromise = supabase
        .from("client_insurance_records")
        .select("id, care_level, start_date:certification_start_date, end_date:certification_end_date")
        .eq("client_id", userId)
        .order("certification_start_date", { ascending: false, nullsFirst: false });

      const [{ data: certData, error: certError }, { data: docData, error: docsError }] =
        await Promise.all([certPromise, docsPromise]);
      if (certError) console.error("certifications fetch failed:", certError.message);
      if (docsError) console.error("report documents fetch failed:", docsError.message);

      initialCertifications = (certData ?? []) as Certification[];
      const initialCertId = initialCertifications[0]?.id ?? null;
      const allDocs = (docData ?? []) as ReportDoc[];
      initialDocs = initialCertId
        ? allDocs.filter((d) => d.certification_id === initialCertId)
        : allDocs;
    } else {
      const { data: docData, error: docsError } = await docsPromise;
      if (docsError) console.error("report documents fetch failed:", docsError.message);
      initialDocs = (docData ?? []) as ReportDoc[];
    }
    // 既存帳票が無いときの「自動生成」は server 側では走らせない。
    // 理由: autoGenerateDoc は 5+ クエリ + INSERT を含み、user 切替の体感を著しく
    // 悪化させる (= 数百 ms 〜 1 秒)。client 側の useEffect で fallback として
    // 起動し、その間は「読み込み中」表示にする。
  }

  return (
    <div className="flex h-full -m-6">
      <UserSidebar />
      {userId ? (
        <ReportsContent
          userId={userId}
          reportType={reportType}
          initialDocs={initialDocs}
          initialCertifications={initialCertifications}
        />
      ) : (
        <div className="flex-1 overflow-y-auto p-6">
          <div className="flex flex-col items-center justify-center py-24 text-gray-400 no-print">
            <FileText size={48} className="mb-4 text-gray-300" />
            <p className="text-base font-medium">左側のリストから利用者を選択してください</p>
          </div>
        </div>
      )}
    </div>
  );
}
