// ============================================================================
// 中身が空のまま二重にできた帳票を消す。
//
//   node migrations/delete_empty_duplicate_reports.mjs            # DRY RUN
//   node migrations/delete_empty_duplicate_reports.mjs --execute
//
// ── なぜ要るか ──────────────────────────────────────────────────────────
//   帳票の自動生成は「一覧が空だったら 1 通作る」で動く。その一覧の取得が
//   失敗・競合すると **中身の無い 2 通目**ができる。2026-08-31 に第1表で
//   6 通できていた (同じ利用者・同じ認定に、本文が 1 つも入っていない帳票)。
//   根本原因は reports-content.tsx の autoGenerateDoc に既存確認を足して塞いだ。
//   これは既にできてしまった分の掃除。
//
// ── 消す条件 (ここを緩めないこと) ──────────────────────────────────────
//   同じ (利用者, 帳票種別, 認定) に 2 通以上あり、かつ
//     ・本文が 1 つも入っていない  (様式ごとに「本文」の定義を持つ)
//     ・明細行も 0 件
//     ・同じ組に **中身のある帳票が残る**
//   の全部を満たすものだけ。1 通しか無いものは中身が空でも消さない
//   (人がこれから書くかもしれないため)。
//
// ── 戻せるようにする ────────────────────────────────────────────────────
//   消す前に全行を migrations/_backup_empty_duplicate_reports_<日付>.json に
//   書き出す。中身ごと保存するので、間違えたら INSERT で戻せる。
// ============================================================================
import { createClient } from "@supabase/supabase-js";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const EXECUTE = process.argv.includes("--execute");
const KAIGO = fileURLToPath(new URL("../", import.meta.url));

const env = Object.fromEntries(
  readFileSync(path.join(KAIGO, ".env.local"), "utf8")
    .split(/\r?\n/)
    .filter((l) => l.includes("=") && !l.trimStart().startsWith("#"))
    .map((l) => { const i = l.indexOf("="); return [l.slice(0, i).trim(), l.slice(i + 1).trim()]; }),
);
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY, {
  auth: { persistSession: false },
});

/**
 * 様式ごとの「本文」。ここが 1 つも入っていなければ中身なしとみなす。
 * 表題部 (氏名・認定など) は自動で入るので判定に使わない。
 */
const BODY_FIELDS = {
  "care-plan-1": ["issue_analysis", "review_opinion", "overall_policy", "living_support_reason"],
  "care-plan-2": ["needs"],
  "care-plan-3": ["schedule", "daily_activities", "other_services"],
  "yobo-care-plan": ["areas", "goals", "target_life_day", "target_life_year", "health_status", "overall_policy"],
};

const hasBody = (reportType, content) => {
  const c = content || {};
  for (const f of BODY_FIELDS[reportType] ?? []) {
    const v = c[f];
    if (Array.isArray(v)) {
      // 配列は「1 つでも中身のある要素があるか」で見る (空の器が並ぶことがある)
      if (v.some((x) => x && Object.values(x).some((y) => y && String(y).trim()))) return true;
    } else if (v && typeof v === "object") {
      if (Object.values(v).some((y) => y && String(y).trim())) return true;
    } else if (v && String(v).trim()) return true;
  }
  // サービス行・明細が入っていれば中身あり
  for (const f of ["services", "entries", "items"]) {
    if (Array.isArray(c[f]) && c[f].length > 0) return true;
  }
  return false;
};

async function fetchAll(build) {
  const out = [];
  const STEP = 1000;
  for (let from = 0; ; from += STEP) {
    const { data, error } = await build().range(from, from + STEP - 1);
    if (error) throw new Error(error.message);
    out.push(...(data ?? []));
    if (!data || data.length < STEP) return out;
  }
}

async function main() {
  console.log("=== 中身が空のまま二重にできた帳票の掃除 ===");
  console.log(EXECUTE ? "*** 本番実行 ***" : "*** DRY RUN (--execute で反映) ***");

  const types = Object.keys(BODY_FIELDS);
  const victims = [];
  for (const type of types) {
    const docs = await fetchAll(() => sb
      .from("kaigo_report_documents")
      .select("*")
      .eq("report_type", type)
      .order("id"));

    // (利用者, 認定) ごとにまとめる
    const groups = new Map();
    for (const d of docs) {
      const k = `${d.user_id}|${d.certification_id ?? "-"}`;
      if (!groups.has(k)) groups.set(k, []);
      groups.get(k).push(d);
    }

    let groupCount = 0;
    for (const arr of groups.values()) {
      if (arr.length < 2) continue;                       // 1 通しか無いものは触らない
      const withBody = arr.filter((d) => hasBody(type, d.content));
      const empty = arr.filter((d) => !hasBody(type, d.content));
      if (withBody.length === 0) continue;                // 全部空 → どれが正か決められないので触らない
      if (empty.length === 0) continue;                   // 全部中身あり → 別月の計画書などなので触らない
      groupCount++;
      for (const d of empty) {
        victims.push({
          type,
          name: String(d.content?.user_name ?? "?"),
          id: d.id,
          created_at: d.created_at,
          残す: withBody.map((w) => `${w.id.slice(0, 8)}(${w.report_month ?? "-"})`).join(","),
          row: d,
        });
      }
    }
    console.log(`  ${type}: ${docs.length} 件 / 空の重複がある組 ${groupCount}`);
  }

  console.log("");
  console.log(`消す ${victims.length} 件:`);
  victims.forEach((v) => console.log(`   ${v.type.padEnd(14)} ${v.name.padEnd(12)} 作成${String(v.created_at).slice(0, 10)} id=${v.id.slice(0, 8)} (残す: ${v.残す})`));
  if (!victims.length) { console.log("  対象なし"); return; }

  if (!EXECUTE) { console.log("\nDRY RUN。--execute で削除する。"); return; }

  // 消す前に中身ごと退避する (間違えたら INSERT で戻せる)
  const stamp = new Date().toISOString().slice(0, 10).replace(/-/g, "");
  const backup = path.join(KAIGO, "migrations", `_backup_empty_duplicate_reports_${stamp}.json`);
  writeFileSync(backup, JSON.stringify(victims.map((v) => v.row), null, 2) + "\n", "utf8");
  console.log(`バックアップ: ${path.relative(KAIGO, backup)}`);

  let ok = 0, ng = 0;
  for (const v of victims) {
    const { error } = await sb.from("kaigo_report_documents").delete().eq("id", v.id);
    if (error) { ng++; console.error(`  ✗ ${v.name}: ${error.message}`); continue; }
    ok++;
  }
  console.log(`\n削除 ${ok} 件 / 失敗 ${ng} 件`);
  if (ng) process.exitCode = 1;
}

main().catch((e) => { console.error(e); process.exit(1); });
